authentication/urls.py
from django.urls import path, include
from django_cas_ng import views as cas_views
from .views import loginApi, loginView, signupApi, signupView, logoutView

urlpatterns = [
  path('api/login/', loginApi, name='loginapi'),
  path('api/signup/', signupApi, name='signupapi'),
  path('login/', loginView, name='login'),
  path('signup/', signupView, name='signup'),
  path('logout/', logoutView, name='logout'),
  path('loginsso/', cas_views.LoginView.as_view(), name='loginsso'),
  path('logoutsso/', cas_views.LogoutView.as_view(), name='logoutsso'),
]

home/urls.py
from django.urls import path
from home.views import index,edit_feedback,delete_feedback,get_data,add_data_flutter


urlpatterns = [
    path('', index,name='index'),
    path('edit_feedback', edit_feedback, name='edit_feedback'),
    path('delete_feedback', delete_feedback, name='delete_feedback'),
    path('get-data/',get_data,name='get_data'),
    path('add-data',add_data_flutter, name='add-data')
    # TODO Add friends path using friend_list Views
]

icovid/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index
from django.conf.urls.static import static
from django.conf import settings
from .views import index
import news.urls as news
import tracker.urls as tracker
from django.conf import settings
import forum.urls as forum
import utilities.urls as utilities


urlpatterns = [
    path('', index),
    path('forum/', include(forum)),
    path('admin/', admin.site.urls),
    path('administrator/', include('utilities.urls')),
    path('profileapp/',include('profileapp.urls')),
    path('', index),
    path('forum/', include(forum)),
    path('tracker/', include(tracker)),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('home/', include(('home.urls', 'home'), namespace='home/')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
import json

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_cas_ng.signals import cas_user_authenticated
from profileapp.models import Profile

@receiver(cas_user_authenticated)
def save_cas_user_attributes(user, attributes, **kwargs):
  """Save attributes for user that authenticated from CAS"""

  full_name = attributes.get('nama', '').split()
  user.first_name = full_name[0]
  user.last_name = full_name[-1]
  user.profile.name = attributes.get('nama', '')

  if (attributes.get('peran_user') == 'mahasiswa'):
    user.email = f'{user.username}@ui.ac.id'
    user.profile.email = f'{user.username}@ui.ac.id'

  user.save()

icovid/authentication/models.py
import json

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_cas_ng.signals import cas_user_authenticated

LANG = settings.SSO_UI_ORG_DETAIL_LANG
ORG_CODE = {}
with open(settings.SSO_UI_ORG_DETAIL_FILE_PATH, 'r') as ORG_CODE_FILE:
  ORG_CODE.update(json.load(ORG_CODE_FILE))


@receiver(cas_user_authenticated)
def save_cas_user_attributes(user, attributes, **kwargs):
  """Save attributes for user that authenticated from CAS"""

  full_name = attributes.get('nama', 'mr. anonymous').split()
  user.first_name = full_name[0]
  user.last_name = full_name[-1]

  if (attributes.get('peran_user') == 'mahasiswa'):
    user.email = f'{user.username}@ui.ac.id'
  
  user.save()

authentication/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelForm, ChoiceField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field
from crispy_forms.bootstrap import PrependedText

class LoginForm(AuthenticationForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.layout = Layout(
      Field(PrependedText('username', '@', placeholder="username")),
      Field('password')
    )

class SignupForm(UserCreationForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.layout = Layout(
      Field(PrependedText('username', '@', placeholder="username")),
      Field('password1'),
      Field('password2')
    )

authentication/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.decorators.csrf import csrf_protect
from .models import User
from .forms import LoginForm, SignupForm
from .utils import request_schema
from . import schema as schema

def loginView(request):
  if(request.user.is_authenticated):
    return redirect('/home')
  
  prop = {
    'type': 'login',
    'form': LoginForm(),
  }
  return render(request, 'index.html', prop)

def signupView(request):
  if(request.user.is_authenticated):
    return redirect('/')
  
  prop = {
    'type': 'signup',
    'form': SignupForm(),
  }
  return render(request, 'index.html', prop)

def logoutView(request):
  logout(request)
  return redirect('/auth/login/')


@csrf_protect
@request_schema(method='POST', schema=schema.login_api_request)
def loginApi(request, data):
  if request.is_ajax:
    user = authenticate(username=data['username'], password=data['password'])

    if user is not None:
      login(request, user)
      return JsonResponse(status=200, data={'message': 'Login Success'})
    else:
      if User.objects.filter(username=data['username']).count():
        return JsonResponse(status=400, data={'message': 'The username and password does\'nt match!'})
      else:
        return JsonResponse(status=400, data={'message': 'There are no user with the given username!'})

  return JsonResponse(status=500, data={'message': 'Internal Server Error'})

@csrf_protect
@request_schema(method='POST', schema=schema.signup_api_request)
def signupApi(request, data):
  if request.is_ajax:
    form = UserCreationForm(data)

    if form.is_valid():
      form.save()
      new_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
      login(request, new_user)
      return JsonResponse(status=200, data={"message": "User registration successful", "username": form.cleaned_data['username']})
    else:
      return JsonResponse(status=400, data={"message": "User registration failed", "error": form.errors})

  return JsonResponse(status=500, data={'message': 'Internal Server Error'})

authentication/templates/index.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='{%  static "css/index.css" %}' rel='stylesheet'>
    <link href='{%  static "css/form.css" %}' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>{{ pagetitle }}</title>
  </head>
  <style>
    body {
      font-family: 'Montserrat';
      display: flex;
      width: auto;
      min-height: 100vh;
      margin: 0;
      background-color: #8aa4c8;
    }
  </style>
  <body>
    <div class="background">
      <div>
        <img class='icovid-logo' src='{% static "icovid.svg" %}'>
        <p class='icovid-text'>ICovid</p>
      </div>
    </div>
    <div class="auth-placeholder">
    {% if type == "login" %}
      {% include "login.html" %} 
    {% elif type == "signup" %}
      {% include "signup.html" %} 
    {% endif %}
    </div>
  </body>
</html>

authentication/templates/login.html
{% load static %}
{% load crispy_forms_tags %}
{% load socialaccount %}

{% block content %}
<div class='auth-form'>
  <div class="w-100">
    <h2 class="login-text">Login</h2>
    <div class="flex-column d-flex align-items-center justify-content-between px-3">
      <form class="mb-3 d-flex flex-column">
        {% csrf_token %}
        {% crispy form %}
        <p id="loading-message"></p>
        <input class="btn btn-outline-primary m-2 mt-4 rounded-pill" id="login-button" type="button" value="Login">
        <a class="btn btn-outline-warning m-2 rounded-pill" href='{% url "authentication:loginsso" %}'>
          Login with SSO UI
        </a>
        <a class="btn btn-outline-success m-2 rounded-pill" href="{% provider_login_url 'google' %}">Login With Google</a>
        <p>Belum punya akun? <a href='{% url "authentication:signup" %}'>Daftar di sini</a></p>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block userscript %}
<script>
  $(document).ready(() => {
    function login(username, password) {
      $.ajax({
        url: '{% url "authentication:loginapi" %}',
        type: 'post',
        headers: {'X-CSRFToken': '{{ csrf_token }}'},
        data: {'username': username, 'password': password},
        beforeSend: function() {
          $("#loading-message").html('Please wait...')
          $('#loading-message').css({'color': 'gray'})
        }
      }).done((response, textStatus, xhr) => { window.location.pathname = '/home/' }
      ).fail((response, textStatus, xhr) => {
          console.log(response.responseJSON.message)
          $("#loading-message").html(response.responseJSON.message)
          $('#loading-message').css({'color': 'red'})
        }
      )
    }
    $('#login-button').click(() => {
      $('#login-button').prop('disabled', true) 
      const username = $.trim($('#id_username').val()) 
      const password = $.trim($('#id_password').val()) 
      
      login(username, password) 
      $('#login-button').prop('disabled', false) 
    })
  }) 
</script>
{% endblock %}

authentication/templates/signup.html
{% load static %}
{% load crispy_forms_tags %}
{% load socialaccount %}

{% block content %}
<div class='auth-form'>
  <div class="w-100">
    <h2 class="login-text">Sign Up</h2>
    <div class="flex-column d-flex align-items-center justify-content-between px-3">
      <form class="mb-3 d-flex flex-column">
        {% csrf_token %}
        {% crispy form %}
        <p id="loading-message"></p>
        <input class="btn btn-outline-primary m-2 mt-4 rounded-pill" id="signup-button" type="button" value="Sign Up">
        <a class="btn btn-outline-warning m-2 rounded-pill" href="{% url 'authentication:loginsso' %}">
          Login with SSO UI
        </a>
        <a class="btn btn-outline-success m-2 rounded-pill" href="{% provider_login_url 'google' %}">Login With Google</a>
        <p>Sudah punya akun? <a href="{% url 'authentication:login' %}">Masuk dari sini</a></p>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block userscript %}
<script>
  $(document).ready(() => {
    function signup(username, password) {
      $.ajax({
        url: '{% url "authentication:signupapi" %}',
        type: 'post',
        headers: {'X-CSRFToken': '{{ csrf_token }}'},
        data: {'username': username, 'password1': password, 'password2': password},
        beforeSend: function() {
          $('#loading-message').empty()
          $("#loading-message").html('Please wait...')
          $('#loading-message').css({'color': 'gray'})
        }
      }).done((response, textStatus, xhr) => { window.location.pathname = '/home/' }
      ).fail((response, textStatus, xhr) => {
          $('#loading-message').empty()
          console.log(response.responseJSON.error)
          $('p.error_messages').remove();
          form_error = response.responseJSON.error
          for (const key in form_error) {
            console.log(form_error[key])
            if (form_error[key] === null) {
              continue;
            }
            form_error[key].forEach((error) => {
              var new_elem = document.createElement("p")
              new_elem.innerHTML = error
              $(new_elem).css({'margin': '0'})
              $(new_elem).addClass('error_messages')
              $(new_elem).css({'color': 'red'})
              $(`#div_id_${key}`).append(new_elem)
            });
          }
        }
      )
    }
    $('#signup-button').click(() => {
      $('#signup-button').prop('disabled', true) 
      const username = $('#id_username').val() 
      const password1 = $('#id_password1').val() 
      const password2 = $('#id_password2').val() 

      if (password1 !== password2) {
        $('#loading-message').empty()
        $('#loading-message').html('Password and confirmation don\'t match')
        $('#loading-message').css({'color': 'red'})
      }else {
        signup(username, password1)
      }

      $('#signup-button').prop('disabled', false) 
    })
  }) 
</script>
{% endblock %}