home/urls.py
from django.urls import path
from home.views import index,edit_feedback,delete_feedback,get_data,add_data_flutter


urlpatterns = [
    path('', index,name='index'),
    path('edit_feedback', edit_feedback, name='edit_feedback'),
    path('delete_feedback', delete_feedback, name='delete_feedback'),
    path('get-data/',get_data,name='get_data'),
    path('add-data',add_data_flutter, name='add-data')
    # TODO Add friends path using friend_list Views
]

icovid/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index
from django.conf.urls.static import static
from django.conf import settings
from .views import index
import news.urls as news
import tracker.urls as tracker
from django.conf import settings
import forum.urls as forum
import utilities.urls as utilities


urlpatterns = [
    path('', index),
    path('forum/', include(forum)),
    path('admin/', admin.site.urls),
    path('administrator/', include('utilities.urls')),
    path('profileapp/',include('profileapp.urls')),
    path('', index),
    path('forum/', include(forum)),
    path('tracker/', include(tracker)),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('home/', include(('home.urls', 'home'), namespace='home/')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utilities/urls.py
from django.urls import path
from .views import make_announcement, get_announcement, see_log

urlpatterns = [
    path('make-announcement', make_announcement, name='make_announcement'),
    path('get-announcement', get_announcement, name='get_announcement'),
    path('', see_log, name='see_log'),
]

utilities/models.py
from django.db import models

# Create your models here.
class Announcement(models.Model):
    title = models.CharField(max_length=200)
    message = models.TextField()
    

utilities/forms.py
from django.forms import ModelForm
from django import forms
from .models import Announcement as AnnouncementModel

class AnnouncementForm(ModelForm):
	class Meta:
		model = AnnouncementModel
		fields = ['title','message']
		
		

utilities/views.py
# Create your views here.
from django.http.response import HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import render
from django.http import JsonResponse
from django.core import serializers
from .models import Announcement
from .forms import AnnouncementForm
from django.contrib.auth.decorators import user_passes_test

@user_passes_test(lambda u: u.is_superuser)
def make_announcement(request):
    form = AnnouncementForm(request.POST or None)

    if (request.method == 'POST'):
        if (form.is_valid):
            form.save()

            return HttpResponseRedirect("/administrator/")
        
    response = {'form': form}
    return render(request, 'utilities_make_announcement.html', response)

@user_passes_test(lambda u: u.is_superuser)
def get_announcement(request):
    announcement = Announcement.objects.all()
    
    data = serializers.serialize('json', announcement)        
    return HttpResponse(data, content_type="application/json")

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

@user_passes_test(lambda u: u.is_superuser)
def see_log(request):
    log_file = open(BASE_DIR/'utilities/log/icovid_log.log','r')
    log_content_dirty = log_file.readlines()
    log_content = [line.strip() for line in log_content_dirty]
    log_file.close()

    response = {'log_content': log_content}
    return render(request, 'utilities_see_log.html', response)

utilities/templates/utilities_choosing_navbar.html
<!-- Choosing navbar based on roles (Guest, User, or Admin) -->
{% if user.is_authenticated %}
	
	<!-- Admin -->
  {% if user.is_superuser %}                      
    {% include 'utilities_navbar_admin.html' %}   

  <!-- User -->  
  {% else %} 
    {% include 'utilities_navbar_user.html' %} 
  {% endif %}             

<!-- Guest -->
{% else %}  
  {% include 'utilities_navbar_guest.html' %} 
   
{% endif %}

utilities/templates/utilities_make_announcement.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>iCovid - Make Announcement</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/utilities_styles.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </head>
  <body id="utilities">
    {% include 'utilities_choosing_navbar.html' %} 
    
    <!-- Make Announcement --> 
    <section class="container-fluid">
      <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-3">
          <form action="" method="POST" id="announcement" class="form-container">
              {% csrf_token %}
              <h4 class="text-center font-weight-bold">Make Announcement</h4>
              <br>
              <div class="form-group">
                <input id="id_title" class="form-control" width="75%" type="text" name="title" required="true" placeholder="Title" />
              </div>
              <div class="form-group">
                <textarea id="id_message" class="form-control" form="announcement" rows="4" cols="100" name="message" required="true" placeholder="Message"></textarea> 
              </div>
              <br>           
              <input type="submit" class="btn btn-primary btn-block" id="announcementSubmit" value="Post">             
          </form>
        </section>
      </section>
    </section>
    <!-- end section -->

    <script type="text/javascript">
      $(document).ready(function() { 
        $("#announcementSubmit").click(function(e) {
          // serialize the data for sending the form data.
          var serializedData = $(this).serialize();
          // make POST ajax call
          $.ajax({
            url: "{% url 'make_announcement' %}",
            type: "POST",
            data: serializedData,             
            success: function(response) {   
              location.reload();
            },
            error: function (response) {
              console.error(response);
            }
          });
        });
      })
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>

utilities/templates/utilities_modal_announcement.html
<!-- Modal Popup Announcement --> 
<div class="modal fade" id="announcementModal" data-keyboard="false" data-backdrop="static" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Announcement</h4>
        <button class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <h5 style="text-align: center;">Title</h5>
        <p style="text-align: center;" id="announcementTitle"></p>
        <br>
        <h5 style="text-align: center;">Message</h5>
        <p style="text-align: center;" id="announcementMessage"></p>
      </div>
      <div class="modal-footer">
        <button class="btn btn-info" data-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>
<!-- end modal -->

utilities/templates/utilities_navbar_admin.html
<!-- link and script -->
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="{% static 'css/utilities_styles.css' %}" />

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- end -->

<!-- Navbar Admin -->
<header id="utilities" style="background-color: #83aae1;">
  <a id="utilities" href="/home/" style="margin-right: auto;"><img class="logo" src="{% static 'images/icovid-logo.png' %}" alt="logo" /></a>
  <div class="drop" id="utilities">
    <button id="utilities" class="dbutton">Admin</button>
    <div class="dcontent" id="utilities">
      <a id="utilities" href="/news/add/"                      >Post article</a>
      <a id="utilities" href="/administrator/make-announcement">Make announcement</a>
      <a id="utilities" href="/administrator/"                 >See log</a>
    </div>
  </div> 
  <nav> 
    <ul class="navibar" id="utilities">
      <li id="utilities"><a id="utilities" href="/home/"       >Home</a></li>  
      <li id="utilities"><a id="utilities" href="/news/"       >News</a></li>
      <li id="utilities"><a id="utilities" href="/forum"       >Forum</a></li>
      <li id="utilities"><a id="utilities" href="/tracker"     >Tracking</a></li>
      <li id="utilities"><a id="utilities" href="/auth/logout/" >Log out</a></li>  
    </ul>
  </nav>
</header>
<!--end navbar-->

<!-- Announcement --> 
<button id="utilities" data-target="#announcementModal" data-toggle="modal" 
style="padding: 5px 15px; margin-top: 10px; background: #ffd4fd; width: 97%; margin-bottom: 10px;" >Announcement</button>

{% include 'utilities_modal_announcement.html' %} 

<script type="text/javascript">
$(document).ready(function() { 
  $.getJSON("/administrator/get-announcement",
  function(data){ 
    $('#announcementTitle').text(data[data.length-1]["fields"]["title"].toLocaleString("en-US"));
    $('#announcementMessage').text(data[data.length-1]["fields"]["message"].toLocaleString("en-US"));
  });      
})
</script>
<!-- end Announcement -->

utilities/templates/utilities_navbar_guest.html
<!-- link and script -->
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="{% static 'css/utilities_styles.css' %}" />

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- end -->

<!-- Navbar Guest -->
<header id="utilities" style="background-color: #83aae1;">
  <a id="utilities" href="/home/" style="margin-right: auto;"><img class="logo" src="{% static 'images/icovid-logo.png' %}" alt="logo" /></a>
  <nav> 
    <ul class="navibar" id="utilities">
      <li id="utilities"><a id="utilities" href="/home/"      >Home</a></li>  
      <li id="utilities"><a id="utilities" href="/news/"      >News</a></li>
      <li id="utilities"><a id="utilities" href="/forum"      >Forum</a></li>
      <li id="utilities"><a id="utilities" href="/tracker/"   >Tracking</a></li>
      <li id="utilities"><a id="utilities" href="/auth/login/" >Log in</a></li>  
    </ul>
  </nav>
  <a id="utilities" href="/auth/signup/"><button id="utilities" style="padding: 5px 15px;">Sign up</button></a>
</header>
<!--end navbar--> 

<!-- Announcement --> 
<button id="utilities" data-target="#announcementModal" data-toggle="modal" 
style="padding: 5px 15px; margin-top: 10px; background: #ffd4fd; width: 97%; margin-bottom: 10px;" >Announcement</button>

{% include 'utilities_modal_announcement.html' %} 

<script type="text/javascript">
$(document).ready(function() { 
  $.getJSON("/administrator/get-announcement",
  function(data){ 
    $('#announcementTitle').text(data[data.length-1]["fields"]["title"].toLocaleString("en-US"));
    $('#announcementMessage').text(data[data.length-1]["fields"]["message"].toLocaleString("en-US"));
  });      
})
</script>
<!-- end Announcement -->

utilities/templates/utilities_navbar_user.html
<!-- link and script -->
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="{% static 'css/utilities_styles.css' %}" />

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- end -->

<!-- Navbar User -->
<header id="utilities" style="background-color: #83aae1;">
  <a id="utilities" href="/home/" style="margin-right: auto;"><img class="logo" src="{% static 'images/icovid-logo.png' %}" alt="logo" /></a>
  <nav> 
    <ul class="navibar" id="utilities">
      <li id="utilities"><a id="utilities" href="/home/"                      >Home</a></li>  
      <li id="utilities"><a id="utilities" href="/news/"                      >News</a></li>
      <li id="utilities"><a id="utilities" href="/forum"                     >Forum</a></li>
      <li id="utilities"><a id="utilities" href="/tracker/"                  >Tracking</a></li>
      <li id="utilities"><a id="utilities" href="/profileapp/profile-page/"  >Profile</a></li>
      <li id="utilities"><a id="utilities" href="/auth/logout/"               >Log out</a></li>  
    </ul>
  </nav>
</header>
<!--end navbar--> 

<!-- Announcement --> 
<button id="utilities" data-target="#announcementModal" data-toggle="modal" 
style="padding: 5px 15px; margin-top: 10px; background: #ffd4fd; width: 97%; margin-bottom: 10px;" >Announcement</button>

{% include 'utilities_modal_announcement.html' %} 

<script type="text/javascript">
$(document).ready(function() { 
  $.getJSON("/administrator/get-announcement",
  function(data){ 
    $('#announcementTitle').text(data[data.length-1]["fields"]["title"].toLocaleString("en-US"));
    $('#announcementMessage').text(data[data.length-1]["fields"]["message"].toLocaleString("en-US"));
  });      
})
</script>
<!-- end Announcement -->

utilities/templates/utilities_see_log.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>iCovid - See Log</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/utilities_styles.css' %}" />

  </head>
  <body id="utilities">
    {% include 'utilities_choosing_navbar.html' %}              

    <!-- See Log in table--> 
    <div class="container mb-5 mt-3">
      <table class="table table-striped table-bordered" id="log-table" 
      style="width: 100%; background: whitesmoke; color: black; border-radius: 15px;">
        <thead>
          <tr>
            <th style="border-radius: 15px 15px 0 0;">Log of iCovid</th>
          </tr>
        </thead>
        <tbody>
          <!-- START LOOP SECTION -->
          {% for line in log_content %}
          <tr>
            <td>{{ line }}</td>
          </tr>  
          {% endfor %}
          <!-- END LOOP SECTION -->
        </tbody>
      </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script type="text/javascript">
      $('#log-table').DataTable({
        ordering: false,
        searching: false,
        lengthMenu:[[10,25,50,100,-1], [10,25,50,100,"All"]]
      });
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>    
  </body>
</html>