home/urls.py
from django.urls import path
from home.views import index,edit_feedback,delete_feedback,get_data,add_data_flutter


urlpatterns = [
    path('', index,name='index'),
    path('edit_feedback', edit_feedback, name='edit_feedback'),
    path('delete_feedback', delete_feedback, name='delete_feedback'),
    path('get-data/',get_data,name='get_data'),
    path('add-data',add_data_flutter, name='add-data')
    # TODO Add friends path using friend_list Views
]

icovid/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index
from django.conf.urls.static import static
from django.conf import settings
from .views import index
import news.urls as news
import tracker.urls as tracker
from django.conf import settings
import forum.urls as forum
import utilities.urls as utilities


urlpatterns = [
    path('', index),
    path('forum/', include(forum)),
    path('admin/', admin.site.urls),
    path('administrator/', include('utilities.urls')),
    path('profileapp/',include('profileapp.urls')),
    path('', index),
    path('forum/', include(forum)),
    path('tracker/', include(tracker)),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('home/', include(('home.urls', 'home'), namespace='home/')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile-page/', views.profile, name='user-profile'),
    path('edit-profile/', views.profileupdate, name='update-profile'), 
    path('profile-datas/', views.profiledatas, name='profile-datas'),
    # path('upload/', views.uploadavatar, name='upload-avatar'),
    path('profile/<int:id>', views.otheruserprofile, name='otherprofile'),
]

profileapp/models.py
from django.db import models
from django.contrib.auth.models import User #extending User models that django provided
from django.db.models.signals import post_save 
from django.contrib.auth.models import User
from django.dispatch import receiver #decorator catch the signal called post_save

from PIL import Image

STATUS_CHOICES=(
    ("Infected", "Infected"),
    ("Not Infected", "Not Infected"),
)
VACCINATED_CHOICES=(
    ("Fully Vaccinated", "Fully Vaccinated"),
    ("Not Vaccinated", "Not Vaccinated"),
    ("First Dose", "First Dose"),
)

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # means: the user deleted, also the profile deleted in database(NOT for vice-versa)
    avatar = models.ImageField(default='default.jpg', upload_to='avatar_pict')
    name = models.CharField(max_length=100, blank=False)
    email = models.EmailField(default='youremail@company.com', blank=False)
    phone = models.CharField(default='', max_length=20, blank=False)
    city = models.CharField(default='', max_length=100, blank=False)
    bio = models.TextField(default='', max_length=250, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Not Infected", blank=False)
    vaccinated_status = models.CharField(max_length=50,choices=VACCINATED_CHOICES, default="", blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} Profile' # out: username Profile

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        # resize avatar to speed up website
        img = Image.open(self.avatar.path)
        if (img.height > 350 or img.width > 350):
            out_size = (350,350)
            img.thumbnail(out_size)
            img.save(self.avatar.path)

profileapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields
from django.forms import widgets
from profileapp.models import Profile

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username',]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__' #show all
        exclude = ['user',]

profileapp/views.py
from collections import namedtuple
import json
from os import name
from typing import BinaryIO
from django.contrib.auth.models import User
from django.http import response
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from profileapp.forms import ProfileUpdateForm, UserUpdateForm
from profileapp.models import Profile
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def profile(request):
    return render(request, 'main_profile.html')
    
@login_required
def profileupdate(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            # profilelist = []
            # data_dict = {}
            # data_dict['name'] = request.POST.get('name')
            # data_dict['avatar'] = request.POST.get('avatar')
            # data_dict['email'] = request.POST.get('email')
            # data_dict['phone'] = request.POST.get('phone')
            # data_dict['city'] = request.POST.get('city')
            # data_dict['bio'] = request.POST.get('bio')
            # data_dict['status'] = request.POST.get('status')
            # data_dict['vaccinated_status'] = request.POST.get('vaccinated_status')
            # profilelist.append(data_dict)
            # return JsonResponse(data_dict, safe=False)
            return redirect('user-profile')
        return redirect('user-profile')
        #     messages.success(request, ('Your profile has been updated!'))
        # else:
        #     messages.error(request, ('Unable to update your profile'))
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        
    context = {
        'user_form' : user_form,
        'profile_form' : profile_form,
    }

    return render(request, 'edit_profile.html', context)

# other user
@login_required
def otheruserprofile(request, id):
    user = User.object.get(name=id)
    return render(request,'other_profile.html', {'user': user})

def profiledatas(request):
    form = Profile.objects.all()
    data = serializers.serialize('json', form)
    return HttpResponse(data, content_type="applications/json")

profileapp/templates/base_profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- TITLE -->
    <title> Profile </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- css for envelope logo -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    {% include "utilities_choosing_navbar.html" %}

  </head>
  <body>
    <!-- Page content-->
    <section class="py-5" style="background-color: #83aae1;font-family: 'Montserrat'">
      <div class="container">
        <div class="bg-opacity-50 rounded-3 py-5 px-4 px-md-5 mb-5">
          {% block content %} {% endblock content %}
        </div>
      </div> 
    </section>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>

profileapp/templates/edit_profile.html
{% extends "base_profile.html" %} {% load crispy_forms_tags %} {% load static %} 

{% block content %}
<div class="edit-profile" style="background-color: whitesmoke;border-radius: 0.5%;box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">
  <div class="card-header">
      <h2 class= "text-center" style="color: #2d1f2c; padding: 1em 0 0.5em 0;"> Edit Profile</h2>
    <!-- <div class="card-body">
      <h4 class="card-title" style="text-align: center; color: #1561A7;">@{{ user.username }}</h4>
      <h4 class="card-title-desc" style="text-align: center; color: #2d1f2c;font-weight: bolder;">{{ user.profile.name }}</h4>
    </div> -->
  </div>
  <!-- FORM -->
  <br>
  <!-- FORM -->
  <div class="row gx-5 justify-content-center" style="color: #1561A7; font-weight: 500; font-size: 17px;">
    <div class="col-md-8" style="font-weight: bold;">
      <!-- method -->
      <form method="POST" id="postform" enctype="multipart/form-data">
        {% csrf_token %}
          <div class="form" id="the_post">
            <!-- #1 -->
            <div class="container">
              <div id= "avatar-box" style="text-align: center;">
                <img class="rounded-circle" src="{{ user.profile.avatar.url }}" style="max-height:350px;width:350px;object-fit: cover;" alt="profile picture"/>
                <div class="p-2">{{ profile_form.avatar|as_crispy_field }} </div>
              </div>
            </div>
            <!-- #2 -->
            <div class="container">
              <div class="d-flex justify-content-center">
                <div class="order-1 p-2">{{ user_form|crispy }} </div>
              </div>
            </div>
            <!-- #3 -->
            <div class="container">
              <div class="d-flex justify-content-center">
                <div class="order-1 p-2"> {{ profile_form.name|as_crispy_field }} </divid>
                <div class="order-2 p-2"> {{ profile_form.email|as_crispy_field }} </div>
              </div>
            </div>
            <!-- #4 -->
            </div class="container">
              <div class="d-flex justify-content-center">
                <div class="order-1 p-2"> {{ profile_form.phone|as_crispy_field }} </div>
                <div class="order-2 p-2"> {{ profile_form.city|as_crispy_field }} </div>
              </div>
            </div>
            <!-- #5 -->
            <div class="container" style="font-weight: bold;">
              <div class="d-flex justify-content-center">
                <div class="order-1 p-2"> {{ profile_form.bio|as_crispy_field }} </div>
              </div>
            </div>
            <!-- #6 -->
            <div class="container" style="font-weight: bold;">
              <div class="d-flex justify-content-center">
                <div class="order-1 p-2"> {{ profile_form.status|as_crispy_field }} </div>
                <div class="order-1 p-2"> {{ profile_form.vaccinated_status|as_crispy_field }} </div>
              </div>
            </div>
          </div>
          <br>
          <!-- #7 -->
          <div class="card-footer fw-bolder">
            <div class="d-flex justify-content-center">
              <div class="order-1 p-2">
                <button class="btn btn-outline-primary" type="submit" id="btnsave" value="POST">Save Changes</button>
              </div>
              <div class="order-2 p-2">
                <a href= "/profileapp/profile-page" class="btn btn-outline-danger" type="reset" id="btncancel">Cancel</a>
              </div>
            </div>
          </div>
      </form>
    </div>
    <!-- <script type="text/javascript">
    <script type="text/javascript">
    $(document).ready(function() {
      $(document).on("submit", "#postform", function(e){
        // prevent from normal form behaviour
        e.preventDefault();
        // serialize the form data  
        var serializedData = $(this).serialize();
        var response = "";
        $.ajax ({
        $.ajax({
          type : 'POST',
          url :  "{% url 'update-profile' %}",
          data : serializedData,
          success : function(response){
            $("#id_name").val(response["name"]);
            // $("#id_avatar").val(response["avatar"]);
            $("#id_avatar").val(response["avatar"]);
            $("#id_email").val(response["email"]);
            $("#id_phone").val(response["phone"]);
            $("#id_city").val(response["city"]);
            $("#id_bio").val(response["bio"]);
            $("#id_status").val(response["status"]);
            $("#id_vaccinated_status").val(response["vaccinated_status"]);
            console.log("checking the ajax..")
            alert("Your profile has been updated!")
          },
          error : function(response){
            console.log(response)
          }
        });
      });
    });
    </script> -->
  </div>
</div>
{% endblock content %}

profileapp/templates/main_profile.html
{% extends "base_profile.html" %} {% load crispy_forms_tags %} {% load static %} 
{% block content %}

{% if user.is_authenticated %}
<div class="justify-content-center flex-wrap" style="box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); border-radius: 0.5%;">
    <div class="card-header bg-light" style="text-align: center;">
        <h2 style="color:#2d1f2c; padding: 1em 0 0.5em 0; text-align: center; font-weight: bolder;"> {{ user.profile.name }} Profile</h2>
        <hr style="width:100%; text-align:center;">
        <img src="{{ user.profile.avatar.url }}" class="card-img-top rounded-circle" alt="profile picture"  style="max-height:400px;width:350px;object-fit: cover; border-radius: 1%;">
        <br>
    <div class="card-body">
        <h4 class="card-title" style="text-align: center; color: #1561A7;">@{{ user.username }}</h4>
        <h4 class="card-title-desc" style="text-align: center; color: #2d1f2c;font-weight: bolder;">{{ user.profile.name }}</h4>
        <a href= "/profileapp/edit-profile" class="border-bottom btn btn-primary text-center"> Edit Profile</a>
    </div>
</div>
    <div class="card">
        <div class="card-body" style="text-align: center;">
            <h3 class="card-title" style="text-align: center; color: #1561A7; font-weight:bolder;">About {{ user.profile.name }}</h3>
            <hr style="width:100%; text-align:center;">
            <div class="row">
                <div class="col-sm-6" style="text-align: left;">
                    <div class="card">
                        <div class="card-header">
                            <h6 class="card-text"><i class="fa fa-envelope" style="font-size:20px;color:#155FA4"></i><b>    {{ user.profile.email }}</b></h6>
                            <h6 class="card-text"><i class="fa fa-phone" style="font-size:24px;color:#155FA4"></i><b>   {{ user.profile.phone }}</b></h6>
                            <h6 class="card-text"><i class="fa fa-map-marker" style="font-size:24px;color:#155FA4"></i><b>  {{ user.profile.city }}</b></h6>
                            <hr style="width:100%; text-align:center;">
                            <h6 class="card-text-acc"><b>account created:</b></h6>
                            <p>{{ user.profile.created_at}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6" style="text-align: left;">
                    <div class="card">
                        <div class="card-header">
                            <h6 class="card-text"><b> Bio: </b></h6>
                                <p>{{ user.profile.bio }} </p>
                            <hr style="width:100%; text-align:center;">
                            <h6 class="card-text-box"> <b>Health Status:</b></h6> <p> {{ user.profile.status }} </p>
                            <h6 class="card-text-box"> <b> Status:</b></h6> <p> {{ user.profile.vaccinated_status }} </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="text-align: center;">
            <script text='javascript'>
                alert("Welcome to your profile!");
                if(navigator.onLine == true) {
                    document.write("🟢 Online");
                }
                else {
                    document.write("🔴 Offline");
                }
            </script>
        </div>
        <br>
    </div>
</div>

{% else %}
<h4> Please signup or login to see more! </h4>
{% endif %}

{% endblock content %}

profileapp/templates/other_profile.html
{% extends "base_profile.html" %} {% load crispy_forms_tags %} {% load static %} 
{% block content %}

{% if user.is_authenticated %}
<div class="justify-content-center flex-wrap" style="box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); border-radius: 0.5%;">
    <div class="card-header bg-gradient" style="text-align: center;">
        <h2 style="color:#2d1f2c; padding: 1em 0 0.5em 0; text-align: center; font-weight: bolder;"> {{ user.profile.name }} Profile</h2>
        <hr style="width:100%; text-align:center;">
        <img src="{{ user.profile.avatar.url }}" class="card-img-top rounded-circle" alt="profile picture"  style="max-height:400px;width:350px;object-fit: cover; border-radius: 1%;">
    <div class="card-body">
        <h4 class="card-title" style="text-align: center; color: #1561A7;">@{{ user.username }}</h4>
        <h4 class="card-title-desc" style="text-align: center; color: #2d1f2c;font-weight: bolder;">{{ user.profile.name }}</h4>
    </div>
</div>
    <div class="card">
        <div class="card-body" style="text-align: center;">
            <h3 class="card-title" style="text-align: center; color: #1561A7; font-weight:bolder;">About {{ user.profile.name }}</h3>
            <hr style="width:100%; text-align:center;">
            <div class="row">
                <div class="col-sm-6" style="text-align: left;">
                    <div class="card">
                        <div class="card-header">
                            <h6 class="card-text"><i class="fa fa-envelope" style="font-size:20px;color:#155FA4"></i><b>    {{ user.profile.email }}</b></h6>
                            <h6 class="card-text"><i class="fa fa-phone" style="font-size:24px;color:#155FA4"></i><b>   {{ user.profile.phone }}</b></h6>
                            <h6 class="card-text"><i class="fa fa-map-marker" style="font-size:24px;color:#155FA4"></i><b>  {{ user.profile.city }}</b></h6>
                            <hr style="width:100%; text-align:center;">
                            <h6 class="card-text-acc"><b>account created:</b></h6>
                            <p>{{ user.profile.created_at}}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6" style="text-align: left;">
                    <div class="card">
                        <div class="card-header">
                            <h6 class="card-text"><b> Bio: </b></h6>
                                <p>{{ user.profile.bio }} </p>
                            <hr style="width:100%; text-align:center;">
                            <h6 class="card-text-box"> <b>Health Status:</b></h6> <p> {{ user.profile.status }} </p>
                            <h6 class="card-text-box"> <b> Status:</b></h6> <p> {{ user.profile.vaccinated_status }} </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div style="text-align: center;">
            <script text='javascript'>
                alert("Welcome to your profile!");
                if(navigator.onLine == true) {
                    document.write("🟢 Online");
                }
                else {
                    document.write("🔴 Offline");
                }
            </script>
        </div>
        <br>
    </div>
</div>

{% else %}
<h4> Please signup or login to see more! </h4>
{% endif %}

{% endblock content %}