home/urls.py
from django.urls import path
from home.views import index,edit_feedback,delete_feedback,get_data,add_data_flutter


urlpatterns = [
    path('', index,name='index'),
    path('edit_feedback', edit_feedback, name='edit_feedback'),
    path('delete_feedback', delete_feedback, name='delete_feedback'),
    path('get-data/',get_data,name='get_data'),
    path('add-data',add_data_flutter, name='add-data')
    # TODO Add friends path using friend_list Views
]

icovid/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index
from django.conf.urls.static import static
from django.conf import settings
from .views import index
import news.urls as news
import tracker.urls as tracker
from django.conf import settings
import forum.urls as forum
import utilities.urls as utilities


urlpatterns = [
    path('', index),
    path('forum/', include(forum)),
    path('admin/', admin.site.urls),
    path('administrator/', include('utilities.urls')),
    path('profileapp/',include('profileapp.urls')),
    path('', index),
    path('forum/', include(forum)),
    path('tracker/', include(tracker)),
    path('auth/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('news/', include(('news.urls', 'news'), namespace='news')),
    path('home/', include(('home.urls', 'home'), namespace='home/')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import index, read, postArticle, load_more, get_article, post_flutter
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index, name = 'index'),
    path('add/', postArticle, name = 'postArticle'),
    path('read/<str:id>/', read, name = 'read'),
    path('load-more', load_more,name='load-more'),
    path('get-article', get_article, name='get-article'),
    path('post-flutter', post_flutter, name='post-flutter')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    postDate = models.DateField()
    articleImage = models.TextField()
    body = models.TextField()
    summary = models.TextField()

news/forms.py
from django import forms
from .models import Article

class articleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            'title',
            'postDate',
            'articleImage',
            'body',
            'summary'
        ]

news/views.py
import collections
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from news.forms import articleForm
from news.models import Article
from django.core import serializers
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from home.forms import FeedbackForm
from home.models import Feedback
from news.models import Article
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.http import JsonResponse
from django.http import HttpResponse
import json 

# Create your views here.
def index(request):

    articleList = list(Article.objects.all())

    if len(articleList) >= 4:
        firstArticle = articleList[len(articleList) - 1]
        nextThreeArticles = articleList[len(articleList) - 4:len(articleList) - 1]
        nextThreeArticles = nextThreeArticles[::-1]

        context = {
        'firstArticle' : firstArticle,
        'nextThreeArticles' : nextThreeArticles,
        'articleList' : articleList
        }
        return render(request, 'news-home.html', context)

    else:
        context = {}
        return render(request, 'no-articles.html', context)

def read(request, id):
    article = Article.objects.get(title=id)
    context = {
        'article' : article
    }
    return render(request, 'news-read.html', context)

@login_required(login_url='/admin/login/')
def postArticle(request):
    context = {}
    if request.method == "POST":
        form = articleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/news/')
    else:
        form = articleForm()
    context['form'] = form
    return render(request, "article-post.html", context)

def load_more(request):

    articleQuer = Article.objects.all()
    articleQuer = articleQuer[::-1]
    articleQuer = articleQuer[1::]

    offset=int(request.POST['offset'])
    limit=3
    posts=articleQuer[offset:limit+offset]
    totalData=Article.objects.count() - 1
    data={}
    posts_json=serializers.serialize('json', posts)
    return JsonResponse(data={
        'posts':posts_json,
        'totalResult':totalData
    })

@csrf_exempt
def get_article(request):
    all_articles = Article.objects.all()

    articles_list = []
    for i in all_articles:
        dict = {
                "title" : i.title,
                "summary" : i.summary,
                "imageURL" : i.articleImage,
                "body" : i.body,
                "postDate" : str(i.postDate),
        }
        articles_list.append(dict)

    # Serialize query set to json
    data = json.dumps(articles_list)

    return HttpResponse(data, content_type='application/json')

@csrf_exempt
def post_flutter(request):
    data = json.loads(request.body)
    form = articleForm(data)
    form.save()

    response = HttpResponse('success')
    response.status_code = 200
    return response

news/templates/article-post.html
{% load static %}

{% include "utilities_choosing_navbar.html" %}

<link href="{% static 'styles.css' %}" rel="stylesheet" />

<form method="POST" enctype="multipart/form-data" class="form-control" style="text-align: center;">
    <h1 class="fw-bolder fs-4 mb-4" >Add an Article</h1>
    <h1 class="fw-bolder fs-6 mb-4" >( Make at least 4 to display them )</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

news/templates/news-home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>iCovid News - Home</title>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body class="d-flex flex-column">
        {% include "utilities_choosing_navbar.html" %}
        <main class="flex-shrink-0">
            <!-- Latest Post-->
            <section class="py-5">
                <div class="container px-5">
                    
                    <h1 class="fw-bolder fs-4 mb-4"> Latest Post
                        {% if request.user.is_superuser %}
                        <a type="button" class="btn btn-primary mb-2" style="margin-left: 15px; padding: 5px;" href="/news/add/">Add an Article</a>
                        {% endif %}
                    </h1>
                    <div class="card border-0 shadow rounded-3 overflow-hidden">
                        <div class="card-body p-0">
                            <div class="row gx-0">
                                <div class="col-lg-6 col-xl-5 py-lg-5">
                                    <div class="p-4 p-md-5">
                                        <div class="h2 fw-bolder">{{firstArticle.title}}</div>
                                        <p>{{ firstArticle.summary }}</p>
                                        <a class="stretched-link text-decoration-none" href="/news/read/{{firstArticle.title}}/">Click to read more<i class="bi bi-arrow-right"></i></a>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-xl-7">
                                    <div class="bg-featured-blog">
                                        <img src = "/news/media/{{ firstArticle.articleImage }}" alt="" width="700" height="380">
                                    </div>
                                </div> 
                            </div>
                        </div>
                    </div>
                    
                </div>
            </section>
            
            <!-- Blog preview section-->
            <section class="py-5">
                <div class="container px-5">
                    <h2 class="fw-bolder fs-4 mb-4">Previous Posts</h2>
                    <div class="row gx-5 post-wrapper">
                        {% for article in nextThreeArticles %}
                        <div class="col-lg-4 mb-5">
                            <div class="card h-100 shadow border-0">
                                <img class="card-img-top" src="/news/media/{{article.articleImage}}" alt="..." width="600" height="220"/>
                                <div class="card-body p-4">
                                    <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">{{article.title}}</div></a>
                                    <p class="card-text mb-0">{{article.summary}}</p>
                                    <a class="stretched-link text-decoration-none" href="/news/read/{{article.title}}/">Click to read more<i class="bi bi-arrow-right"></i>
                                    </a>
                                </div>
                                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                    <div class="d-flex align-items-end justify-content-between">
                                        <div class="d-flex align-items-center">
                                            <div class="small">
                                                <div class="text-muted">{{article.postDate}}</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        
                    </div>
                    {% if articleList|length > 4 %}
                    <button class="btn btn-dark" id="loadmoreBtn" style="background-color:rgb(13,110,253); border: none;">Load More</button>
                    {% endif %}
                    
                    
                </div>
            </section>
        </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> 
        <script>
            $(document).ready(function(){
                $("#loadmoreBtn").on('click',function(){
                    var _currentResult=$(".mb-5").length;
                    // Run Ajax
                    $.ajax({
                        url:"{% url 'news:load-more' %}",
                        type:'post',
                        data:{
                            'offset':_currentResult,
                            'csrfmiddlewaretoken':"{{csrf_token}}"
                        },
                        dataType:'json',
                        beforeSend:function(){
                            $("#loadmoreBtn").addClass('disabled').text('Loading..');
                        },
                        success:function(res){
                            var _html='';
                            var json_data=$.parseJSON(res.posts);
                            console.log("test")
                            $.each(json_data,function(index,data){
                                _html+='<div class="col-lg-4 mb-5">\
                            <div class="card h-100 shadow border-0">\
                                <img class="card-img-top" src="/news/media/'+data.fields.articleImage+'/" alt="..." width="600" height="220"/>\
                                <div class="card-body p-4">\
                                    <a class="text-decoration-none link-dark stretched-link" href="#!"><div class="h5 card-title mb-3">'+data.fields.title+'</div></a>\
                                    <p class="card-text mb-0">'+data.fields.summary+'</p>\
                                    <a class="stretched-link text-decoration-none" href="./read/'+data.fields.title.replaceAll(" ", "%20").replaceAll("?", "%3F").replaceAll(".", "%2E").replaceAll(",", "%2C").replaceAll("!", "%21") + '/'+'">Click to read more<i class="bi bi-arrow-right"></i></a>\
                                </div>\
                                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">\
                                    <div class="d-flex align-items-end justify-content-between">\
                                        <div class="d-flex align-items-center">\
                                            <div class="small">\
                                                <div class="text-muted">'+data.fields.postDate+'</div>\
                                            </div>\
                                        </div>\
                                    </div>\
                                </div>\
                            </div>\
                        </div>';
                            });
                            $(".post-wrapper").append(_html);
                            var _countTotal=$(".mb-5").length;
                            if(_countTotal==res.totalResult){
                                $("#loadmoreBtn").remove();
                            }else{
                                $("#loadmoreBtn").removeClass('disabled').text('Load More');
                            }
                        }
                    });
                });
            });
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </body>
</html>

news/templates/news-read.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{{article.title}}</title>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'styles.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column">
        {% include "utilities_choosing_navbar.html" %}
        <main class="flex-shrink-0">
            <!-- Page Content-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    <div class="row gx-5">
                        <div class="col-lg-2">
                        </div>
                        <div class="col-lg-9">  
                            <!-- Post content-->
                            <article>
                                <!-- Post header-->
                                <header class="mb-4">
                                    <!-- Post title-->
                                    <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                                    <!-- Post meta content-->
                                    <div class="text-muted fst-italic mb-2">{{article.postDate}}</div>
                                    <!-- Post categories-->
                                </header>
                                <!-- Preview image figure-->
                                <figure class="mb-4"><img class="img-fluid rounded" src="/news/media/{{ article.articleImage }}" alt="..." height = "400px" width="900"/></figure>
                                <!-- Post content-->
                                <section class="mb-5">
                                    <p class="fs-5 mb-4" style="text-align: justify;">{{ article.body }}</p>
                                </section>
                            </article>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </body>
</html>

news/templates/no-articles.html
{% load static %}

{% include "utilities_choosing_navbar.html" %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>iCovid News - Home</title>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body class="d-flex flex-column">
        <main class="flex-shrink-0">
            <!-- Latest Post-->
            <section class="py-5">
                <div class="container px-5">
                    <h1 class="fw-bolder fs-4 mb-4" style="text-align: center;"> There are no articles to display
                        {% if request.user.is_superuser %}
                        <a type="button" class="btn btn-primary mb-2" style="margin-left: 15px; padding: 5px;" href="/news/add/">Add an Article</a>
                        {% endif %}
                    </h1>
                </div>
            </section>
        </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </body>
</html>